version: "3"
services:
  imapwizard:
    image: .
    restart: unless-stopped
    container_name: "imapwizard"
    volumes:
      - /path/to/database:/app/database
    environment:
      - a=b

  nginxrp:
    image: nginx:latest
    container_name: imapwizard_nginx
    restart: unless-stopped
    ports:
      - 6699:80
    depends_on:
      - imapwizard
    